# Generated by Django 3.0.6 on 2020-05-25 08:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('name', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='年级名')),
            ],
            options={
                'verbose_name': '年级',
                'verbose_name_plural': '年级',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='学科名')),
            ],
            options={
                'verbose_name': '学科',
                'verbose_name_plural': '学科',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='标签名')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.Subject')),
                ('super_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loader.Tag', verbose_name='上级标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('question_text', models.TextField()),
                ('type', models.CharField(choices=[('MC', '选择题'), ('TF', '判断题'), ('ES', '主观题'), ('FB', '文字填空题'), ('NM', '数字填空题')], default='ES', max_length=2, verbose_name='题型')),
                ('media_path', models.CharField(max_length=200)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loader.Grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.Subject')),
                ('tag', models.ManyToManyField(to='loader.Tag')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['id'],
            },
        ),
    ]
