# Generated by Django 3.0.6 on 2020-05-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='media_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
