# Generated by Django 3.0.6 on 2020-06-02 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_auto_20200525_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MC', '选择题'), ('TF', '判断题'), ('ES', '主观题'), ('FB', '文字填空题'), ('NM', '数字填空题'), ('MA', '多选题')], default='ES', max_length=2, verbose_name='题型')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_question', models.IntegerField(verbose_name='题号')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.Question')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.Type')),
            ],
            options={
                'ordering': ['sub_question'],
                'unique_together': {('question', 'type', 'sub_question')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ManyToManyField(through='loader.QuestionType', to='loader.Type'),
        ),
    ]
