# Generated by Django 3.0.6 on 2020-06-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0003_auto_20200602_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('MC', '选择题'), ('TF', '判断题'), ('ES', '主观题'), ('FB', '文字填空题'), ('NM', '数字填空题'), ('MA', '多选题')], default='ES', max_length=2, unique=True, verbose_name='题型'),
        ),
    ]
